apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app  : {{ .Release.Name }}-app
    env  : prod
    owner: Foxtrot1388
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : service-profile
          image: {{ .Values.container.image}}
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
            - containerPort: 8082
          env:
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "root"
          - name: POSTGRES_HOST
            value: "{{ .Release.Name }}-db-service"
          - name: POSTGRES_PORT
            value: "5432"
          - name: SIGNING_KEY
            value: "example"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
     env  : prod
     owner: Foxtrot1388
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name      : app-listener-grpc
      protocol  : TCP
      port      : 8081
      targetPort: 8081
    - name      : app-listener-http
      protocol  : TCP
      port      : 8082
      targetPort: 8082
  type: NodePort