apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-internet-magazine-profile
  labels:
    app  : my-internet-magazine-app
    env  : prod
    owner: Foxtrot1388
spec:
  selector:
    matchLabels:
      project: my-internet-magazine-profile
  template:
    metadata:
      labels:
        project: my-internet-magazine-profile
    spec:
      containers:
        - name : service-profile
          image: myinternetmagazine-profile:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "root"
          - name: POSTGRES_HOST
            value: "my-internet-magazine-db-service"
          - name: POSTGRES_PORT
            value: "5432"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: profile-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-internet-magazine-profile
  minReplicas: 2
  maxReplicas: 6

---
apiVersion: v1
kind: Service
metadata:
  name: my-internet-magazine-service
  labels:
     env  : prod
     owner: Foxtrot1388
spec:
  selector:
    project: my-internet-magazine-profile
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8081
      targetPort: 8081
  type: NodePort

---
apiVersion : v1
kind: Pod
metadata:
  name: pgdb-profile
  labels:
    app  : my-internet-magazine-app
    env  : prod
    owner: Foxtrot1388
    project: my-internet-magazine-db-profile
spec:
  containers:
    - name : pgdb-profile
      image: postgres
      ports:
        - containerPort: 5432
      env:
      - name: POSTGRES_USER
        value: "root"
      - name: POSTGRES_PASSWORD
        value: "root"
      - name: POSTGRES_DB
        value: "Profile"

---
apiVersion: v1
kind: Service
metadata:
  name: my-internet-magazine-db-service
  labels:
     env  : prod
     owner: Foxtrot1388
spec:
  selector:
    project: my-internet-magazine-db-profile
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 5432
      targetPort: 5432
  type: ClusterIP