version: '3.8'
services:

  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.4.6
    restart: always
    volumes:
      - "./krakend.json:/etc/krakend/krakend.json"
      - "./pb/:/etc/krakend/pb/"
    networks:
      - myinternetmagazine
    ports:
      - "8080:8080"
    command: ["run","-c","krakend.json"]

  db_profile:
    container_name: pgdb_profile
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Profile
    networks:
    - myinternetmagazine

  db_catalog:
    container_name: pgdb_catalog
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Catalog
    networks:
    - myinternetmagazine

  redis_catalog:
    container_name: redisca_catalog
    image: redis:4.0-alpine
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
    networks:
    - myinternetmagazine

  pgadmin:
    container_name: pgadminmyinternetmagazine
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
    - myinternetmagazine

  profile:
    container_name: service_profile
    build:
      context: ./service-profile
      dockerfile: ./Dockerfile
    restart: always
    networks:
    - myinternetmagazine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: pgdb_profile
      POSTGRES_PORT: 5432
    depends_on:
      - db_profile

  catalog:
    container_name: service_catalog
    build:
      context: ./service-catalog
      dockerfile: ./Dockerfile
    restart: always
    networks:
    - myinternetmagazine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: pgdb_catalog
      POSTGRES_PORT: 5432
      REDIS_HOST: redisca_catalog
      REDIS_PORT: 6379
    depends_on:
      - db_catalog
      - redis_catalog

networks:
  myinternetmagazine:
    driver: bridge