basePath: /
definitions:
  httpapi.createResponse:
    properties:
      id:
        type: integer
    type: object
  httpapi.deleteResponse:
    properties:
      ok:
        type: boolean
    type: object
  httpapi.getResponse:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  httpapi.newCatalog:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  httpapi.response:
    properties:
      message:
        type: string
    type: object
  httpapi.responseElement:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: API Server for catalog
  title: Catalog API
  version: "1.0"
paths:
  /catalog/:
    get:
      description: create
      operationId: list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/httpapi.responseElement'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpapi.response'
      summary: List
      tags:
      - catalog
  /catalog/{catalog_id}:
    delete:
      description: delete
      operationId: delete
      parameters:
      - description: Product ID
        in: path
        name: catalog_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpapi.deleteResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpapi.response'
      summary: Delete
      tags:
      - catalog
    get:
      description: get
      operationId: get
      parameters:
      - description: Product ID
        in: path
        name: catalog_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpapi.getResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpapi.response'
      summary: Get
      tags:
      - catalog
  /catalog/new:
    post:
      consumes:
      - application/json
      description: create
      operationId: create
      parameters:
      - description: new
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/httpapi.newCatalog'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpapi.createResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpapi.response'
      summary: Create
      tags:
      - catalog
  /healthz:
    get:
      consumes:
      - application/json
      description: used by Kubernetes liveness probe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Liveness check
      tags:
      - Kubernetes
  /readyz:
    get:
      consumes:
      - application/json
      description: used by Kubernetes readiness probe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Readiness check
      tags:
      - Kubernetes
  /readyz/disable:
    post:
      consumes:
      - application/json
      description: signals the Kubernetes LB to stop sending requests to this instance
      produces:
      - application/json
      responses:
        "202":
          description: OK
          schema:
            type: string
      summary: Disable ready state
      tags:
      - Kubernetes
  /readyz/enable:
    post:
      consumes:
      - application/json
      description: signals the Kubernetes LB that this instance is ready to receive
        traffic
      produces:
      - application/json
      responses:
        "202":
          description: OK
          schema:
            type: string
      summary: Enable ready state
      tags:
      - Kubernetes
swagger: "2.0"
