version: '3.8'
services:

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otelconfig:/etc/otelcol-contrib
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - myinternetmagazine

  db_catalog:
    container_name: pgdb_catalog
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Catalog
    ports:
    - "5432:5432"
    networks:
    - myinternetmagazine

  redis_catalog:
    container_name: redisca_catalog
    image: redis:4.0-alpine
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
    ports:
    - "6379:6379"
    networks:
    - myinternetmagazine

  catalog:
    container_name: service_catalog
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
    - myinternetmagazine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: pgdb_catalog
      POSTGRES_PORT: 5432
      REDIS_HOST: redisca_catalog
      REDIS_PORT: 6379
    ports:
    - "8081:8081"
    - "8082:8082"
    depends_on:
      - db_catalog
      - redis_catalog
      - otel-collector

networks:
  myinternetmagazine:
    driver: bridge