apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app  : {{ .Release.Name }}-app
    env  : prod
    owner: Foxtrot1388
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : service-catalog
          image: {{ .Values.container.image}}
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
            - containerPort: 8082
          env:
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "root"
          - name: POSTGRES_HOST
            value: "{{ .Release.Name }}-db-service"
          - name: POSTGRES_PORT
            value: "5432"
          - name: REDIS_HOST
            value: "{{ .Release.Name }}-db-cashe"
          - name: REDIS_PORT
            value: "6379"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
     env  : prod
     owner: Foxtrot1388
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name      : app-listener-grpc
      protocol  : TCP
      port      : 8081
      targetPort: 8081
    - name      : app-listener-http
      protocol  : TCP
      port      : 8082
      targetPort: 8082
  type: NodePort

---
apiVersion : v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-cashe
  labels:
    app  : {{ .Release.Name }}-app
    env  : prod
    owner: Foxtrot1388
    project: {{ .Release.Name }}-db-cashe
spec:
  containers:
    - name : {{ .Release.Name }}-cashe
      image: {{ .Values.container.cashe }}
      command: [ "redis-server", "--loglevel warning", "--databases 2" ]
      ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-cashe
  labels:
     env  : prod
     owner: Foxtrot1388
spec:
  selector:
    project: {{ .Release.Name }}-db-cashe
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 6379
      targetPort: 6379
  type: ClusterIP