apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/catalog"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pv-claim  # Sets name of PVC
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size

---
apiVersion : apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app  : {{ .Release.Name }}-app
    env  : prod
    owner: Foxtrot1388
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}-db
  serviceName: "pgdb"
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}-db
    spec:
      containers:
        - name : pgdb
          image: {{ .Values.container.dbimage }}
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: {{ .Release.Name }}-postgredb
            mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "root"
          - name: POSTGRES_DB
            value: "Catalog"
      volumes:
        - name: {{ .Release.Name }}-postgredb
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
  labels:
     env  : prod
     owner: Foxtrot1388
spec:
  selector:
    project: {{ .Release.Name }}-db
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 5432
      targetPort: 5432
  type: ClusterIP